dist:
    - xenial

language:
    - cpp

compiler:
    - clang

## Safelist
#branches:
#    only:
#        - master
#        - ci

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y qtbase5-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j
