image: gcc:6.5

pipelines:
    default:
        - step:
            script:
                - apt-get update && apt-get install -y cmake
                - mkdir build && cd build
                - cmake ..
                - make -j

